from flask import Blueprint, render_template, request

diet = Blueprint('diet', __name__)

def new_diet(diet):
    global current_index
    item = diet[current_index]
    current_index = (current_index + 1) % len(diet)
    return item

@diet.route('/diet', methods=['POST'])
def return_diet():
    is_veg = str(request.form.get('is_veg')).lower()
    is_non_veg = str(request.form.get('is_non_veg')).lower()
    eat_protein_powder = str(request.form.get('protein_powder_yes')).lower()

    veg_diet_powder = ['1. Breakfast:  Veg protein pancakes\n2. Lunch: salad with mixed veggies\n3. Snack: Hummus and raw vegetable sticks\n4. Dinner: vegetable stew with a side of whole grain bread','1. Breakfast: Veg protein smoothie with spinach, banana,almond milk\n2. Lunch: Chickpea salad with lemon\n3. Snack: Mixed nuts and dried fruits\n4. Dinner: chili with beans,roasted chickpeas, and a side of avocado','1. Breakfast: Protein-infused oatmeal with sliced almonds\n2. Lunch: roasted tofu or roasted panner,cucumber with a side of whole grain bread\n3. Snack: Apple slices with almond,butter\n4. Spaghetti with tofu or panner','1. Breakfast: Veg protein muffins with a side of fresh fruit\n2. Lunch: black bean salad with vinegar\n3. Snack: Rice cakes with peanut butter\n4. Dinner: Stir-fried tofu and mixed vegetables, served over brown rice','1. Breakfast: Vegan protein pancakes made with plant-based protein powder.Top with fresh berries and a drizzle of honey.\n2. Lunch: Vegan wrap with falafel, veggies, and tahini sauce\n3. Snack: Carrot and celery sticks with hummus\n4. Dinner: Veg curry with chickpeas and brown rice','1. Breakfast: Vegan protein power bowl with granola, almond yogurt, and fresh fruit\n2. Lunch:  vegetable soup with a side of whole grain bread\n3. protien cookies with milk\n4. Dinner: Veg stir-fry with tofu, broccoli, and a ginger-soy sauce','1. Breakfast: Vegan protein waffles topped with dairy-free yogurt and mixed fruit\n2. Lunch: Vegan burrito bowl with black beans, rice, salsa\n3. Snack: Vegan protein bar or a homemade protein ball\n4. Dinner: roasted soyabean and a side salad']
    veg_diet_nopowder = ['1. Breakfast: Veg yogurt with mixed berries and granola.\n2. Lunch: salad with chickpeas, cucumber, and a tahini dressing.\n3. Snack: Sliced bell peppers with hummus.\n4.Dinner: Eggplant and chickpea stew with a side of whole wheat bread.','1. Breakfast: Avocado toast with cherry tomatoes and a sprinkle of nutritional yeast.\n2. Lunch: Vegan bean and vegetable burrito.\n3. Snack: Mango and chili-lime spiced sticks.\n4. Dinner: Veg chili with kidney beans and a side of brown rice.','1. Breakfast: Vegan rice porridge with coconut milk and a dash of maple syrup.\n2. Lunch: Veg rolls with avocado, cucumber, and sweet potato.\n3. Snack: peas with sea salt and spices.\n4. Dinner: Stir-fried tofu with broccoli and bell peppers in a ginger-soy sauce, served over brown rice.','1. Breakfast: Vegan bruschetta with diced tomatoes, garlic, and basil on whole grain bread.\n2. Lunch: Vegan pasta primavera with mixed vegetables in a tomato-basil sauce.\n3. Snack: Roasted chickpeas.\n4. Dinner: Vegan eggplant Parmesan with a side salad.','Breakfast: Vegan hummus toast with diced cucumbers and cherry tomatoes.\n2.Lunch: Falafel wrap with tahini sauce and a side of salad.\n3.Snack: Sliced oranges with a sprinkle of cinnamon.\n4. congrats on following the diet you can eat whatever you want for dinner today','1. Breakfast: Green smoothie with spinach, banana, almond milk, and a scoop of peanut butter.\n2. Lunch: Veg soup with a side of whole wheat bread.\n3. Snack: Celery and carrot sticks with almond butter.\nDinner: Veg white bean stew with a side of whole grain bread.','1. Breakfast: Vegan breakfast burrito with tofu scramble, black beans, and salsa.\n2. Lunch: Vegan black bean and corn salad with a cilantro-lime vinaigrette.\n3. Snack: Sliced bell peppers with guacamole.\n4. Dinner: Vegan enchiladas with a side of Mexican-style rice.']
    non_veg_diet_powder = ['1. Breakfast: Protein smoothie with whey protein, spinach, banana, and almond milk.\n2. Lunch: Grilled chicken breast salad with mixed greens.\n3. Snack: Greek yogurt with honey and walnuts.\n4. Dinner: Baked salmon and steamed broccoli.','1. Breakfast: Protein pancakes made with whey protein and topped with fresh berries.\n2. Lunch: Lean ground beef and black bean chili.\n3. Snack: Cottage cheese with pineapple.\n4. Dinner: Grilled shrimp skewers with a side of salted spinach and brown rice.','1. Breakfast: Protein smoothie with turkey breast, spinach, avocado, and almond milk.\n2. Lunch: Turkey and lentil soup.\n3. Snack: Hard-boiled eggs.\n4. Dinner: Grilled turkey cutlets with a chickpea and vegetable stir-fry.','1. Breakfast: Protein oatmeal with whey protein, and mixed berries.\n2. Lunch: tofu or panner salad sandwich with mixed greens on whole grain bread.\n3. Snack: Greek yogurt with sliced almonds.\n4. Dinner: Baked cod and roasted sprouts.','1. Breakfast: Protein waffles made with whey protein and topped with sliced berries.\n2. Lunch: Pulled chicken sandwich.\n3. Snack: Cottage cheese with sliced strawberries.\n4. Dinner: Grilled chicken and sweet potato.','1. Breakfast: Protein smoothie with whey protein, mango, and coconut water.\n2. Lunch: Grilled fish and vegetable salad.\n3. Snack: Greek yogurt with honey and nachos.\n4. Dinner: roasted sprout with a side of brown rice and steamed broccoli.','1. Breakfast: Omelette with diced ham, spinach, and cheese.\n2. Lunch: Chicken and vegetable stir-fry with brown rice.\n3. Snack: Cottage cheese with blueberries.\n4. Dinner: Beef stir-fry with broccoli, bell peppers']
    non_veg_diet_nopowder = ['1. Breakfast: Greek yogurt with mixed berries and a drizzle of honey.\n2. Lunch: Grilled chicken breast salad with mixed greens.\n3. Snack: Greek yogurt with honey and walnuts.\n4. Dinner: Baked salmon and steamed broccoli.','1. Breakfast: Scrambled eggs with spinach, tomatoes, and a sprinkle of cheese.\n2. Lunch: Lean ground beef and black bean chili.\n3. Snack: Cottage cheese with pineapple.\n4. Dinner: Grilled shrimp skewers with a side of salted spinach and brown rice.','1. Breakfast: Turkey sausage and vegetable omelette.\n2. Lunch: Turkey and lentil soup.\n3. Snack: Hard-boiled eggs.\n4. Dinner: Grilled turkey cutlets with a chickpea and vegetable stir-fry.','1. Breakfast: Smoked salmon on whole-grain toast with avocado.\n2. Lunch: tofu or panner salad sandwich with mixed greens on whole grain bread.\n3. Snack: Greek yogurt with sliced almonds.\n4. Dinner: Baked cod and roasted sprouts.','1. Breakfast: Scrambled eggs with diced ham.\n2. Lunch: Pulled chicken sandwich.\n3. Snack: Cottage cheese with sliced strawberries.\n4. Dinner: Grilled chicken and sweet potato.','1. Breakfast: Shrimp and vegetable stir-fry with brown rice.\n2. Lunch: Grilled fish and vegetable salad.\n3. Snack: Greek yogurt with honey and nachos.\n4. Dinner: roasted sprout with a side of brown rice and steamed broccoli.','1. Breakfast: Omelette with diced ham, spinach, and cheese.\n2. Lunch: Chicken and vegetable stir-fry with brown rice.\n3. Snack: Cottage cheese with blueberries.\n4. Dinner: Beef stir-fry with broccoli, bell peppers']
    
    if is_veg == 'yes' and is_non_veg == 'no' and eat_protein_powder == 'yes':
        next_item = new_diet(veg_diet_powder)
    elif is_veg == 'yes' and is_non_veg == 'no' and eat_protein_powder == 'no':
        next_item = new_diet(veg_diet_nopowder)
    elif is_veg == 'no' and is_non_veg == 'yes' and eat_protein_powder == 'yes':
        next_item = new_diet(non_veg_diet_powder)
    elif is_veg == 'no' and is_non_veg == 'yes' and eat_protein_powder == 'no':
        next_item = new_diet(non_veg_diet_nopowder)
    return render_template('daily_diet.html', next_item=next_item)